config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get  '/book',    to: 'books#search'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/create',  to: 'static_pages#create'
  resources :users

  resources :books do
    member do #本一覧画面からお気に入り登録をする
      post "add", to: "favorites#create"
    end
  end
  #個人ページからお気に入りを削除する
  resources :favorites, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save{ email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :city,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
     # ユーザーログイン後にユーザー情報のページにリダイレクトする
     log_in user
     redirect_to user
   else
     # エラーメッセージを作成する
     flash.now[:danger] = 'Invalid email/password combination' # 本当は正しくない
     render 'new'
   end
 end


  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @test = User.find(session[:user_id])
    end

  end

  def help
    require 'rakuten_web_service'
    require 'net/http'
    require 'uri'
    require 'json'
    require 'open-uri'
    require 'kconv'
    require 'active_support/core_ext/hash/conversions'


  RWS.configuration do |c|
    c.application_id = '1093362645588395413'
  end

  if params[:keyword].present?
   @books = RWS::Books::Book.search(:title =>"#{params[:keyword]}")
 else
   @books = RWS::Books::Book.search(:title =>"実験")
 end

 if logged_in?
   @test = User.find(session[:user_id])
   url  = URI.encode('http://api.calil.jp/library?limit=10'+"&pref=#{@test.pref}"+"&city=#{@test.city}")
   xml  = open( url ).read.toutf8
   @hash = Hash.from_xml(xml)
   @hash['Libraries']['Library'].each do |a|
   @systemid=a['systemid']
   end
 else
   @systemid = "Tokyo_NDL"
 end

 @items=[]
@books.each do |book|
  @data = {}
  uri = URI.parse('http://api.calil.jp/check?appkey={1f797b9d960207280336610120edb44a}&isbn='+"#{book['isbn']}"+'&systemid='+"#{@systemid}"+'&callback=')
  json = Net::HTTP.get(uri)
  json = json.slice(1..-3)
  result = JSON.parse(json)
  uri = URI.parse('http://api.calil.jp/check?session='+"#{result["session"]}"+'&callback=')
  json = Net::HTTP.get(uri)
  json = json.slice(1..-3)
  result = JSON.parse(json)
  @data["title"]="#{book.title}"
  @data["isbn"]="#{book['isbn']}"
  @data["price"]="#{book['itemPrice']}"
  @data["Pref"]="#{book['itemUrl']}"
  @data["libkey"]=result['books']["#{book['isbn']}"]["#{@systemid}"]["libkey"]
  @data["place"]=[]
  @data["reserve"]=result['books']["#{book['isbn']}"]["#{@systemid}"]["reserveurl"]
  @data["img"]=book['mediumImageUrl']
  @items.push(@data)
end


end

  def about
    require 'uri'
    require 'open-uri'
    require 'kconv'
    require 'active_support/core_ext/hash/conversions'

    url  = URI.encode('http://api.calil.jp/library?limit=10'+'&pref=神奈川県')
    xml  = open( url ).read.toutf8
    @hash = Hash.from_xml(xml)


  end

  def contact
    require 'rakuten_web_service'
    require 'net/http'
    require 'uri'
    require 'json'

  RWS.configuration do |c|
    c.application_id = '1093362645588395413'
  end

  if params[:keyword].present?
   @books = RWS::Books::Book.search(:title =>"#{params[:keyword]}")
 else
   @books = RWS::Books::Book.search(:title =>"デフォルト")
 end

    uri = URI.parse('http://api.calil.jp/check?appkey={1f797b9d960207280336610120edb44a}&isbn=9784101001609&systemid=Kanagawa_Atsugi&callback=')
    json = Net::HTTP.get(uri)
    json = json.slice(1..-3)
    result = JSON.parse(json)





  end

  def create
    @book = params[:book]
    @user_id = session[:id] #ログインしたユーザのID
    @book_id = @book.first #特定の本のID
    #book_idに@book_id、user_idに@user_idを入れて、Favoriteモデルに新しいオブジェクトを作る
    @favorite = Favo.new(book_id: @book_id, user_id: @user_id)
    @favorite.save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    require 'uri'
    require 'open-uri'
    require 'kconv'
    require 'active_support/core_ext/hash/conversions'
    @user = User.find(params[:id])

    #@favorites = Favorite.where("user_id = ?", @user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      #保存の成功をここで扱う。
      flash[:success] = "ようこそ、Buy or Rentへ！！"
      redirect_to @user
    else
      render 'new'
    end


  end

  def edit
    @user = User.find(params[:id])
  end

  private

   def user_params
     params.require(:user).permit(:name, :email, :password,
     :password_confirmation, :city, :pref)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Buy or Borrow"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
 def logged_in?
   !current_user.nil?
 end

 #現在のユーザーをログアウトする
 def log_out
   session.delete(:user_id)
   @current_user = nil
 end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=3{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
   
 </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Buy or Borrow", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "検索", help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<% @books.each do |book| %>
    <div class="list">
      <%= link_to (image_tag(book['mediumImageUrl'])) %>
      <%= link_to "#{book.title}", controller: 'static_pages', action: 'contact',
			name: book['isbn'] %>

    </div>
 <% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "検索") %>
<%= form_tag('/help', method: :get) do %>　
    <%= text_field_tag :book, "",  id: "book_search", name: "keyword", placeholder: "キーワードを打ち込んでください", style: "width: 200px;"%><button title="検索" type="submit">検索</button>
<% end %>
<% if logged_in? %>
 <h3><%= @test.pref %> <%= @test.city %>の図書館</h3>
 <% else %>
 <h3>ログインしてください<h3>
<% end %>
<h2>検索結果</h2>


 <% @items.each do |book| %>
    <div class="list">
      <table>
      <tr>
      <th> <%= image_tag(book["img"]) %> </th>
      <th>
        <ul>
        <li><%= "#{book["title"]}"%></li>
        <li><%= link_to "#{book['price']}"+"円(楽天)","#{book['Pref']}"%></li>
      <li>
      <% if book["libkey"].nil? %>
      <h4>ページを更新してください</h4>
      <% else %>
      <% book["libkey"].keys.each do |status| %>
      <%= status %>:<%= link_to "#{book["libkey"]["#{status}"]}","#{book["reserve"]}" %>
      <% end %>
      <% end %>
      </li>
    </ul>

    </table>
    </div>
 <% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Buy or Borrowへ<br>ようこそ</h1>




  <h2>

  </h2>

  <%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "氏名" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード再入力" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :pref %>
      <%= f.select :pref, [['北海道','北海道'],['青森県','青森県'], ['岩手県',   '岩手県'],
        ['宮城県',   '宮城県'],
        ['秋田県',   '秋田県'],
        ['山形県',   '山形県'],
        ['福島県',   '福島県'],
        ['茨城県',    '茨城県'],
        ['栃木県',   '栃木県'],
        ['群馬県',   '群馬県'],
        ['埼玉県',   '埼玉県'],
        ['千葉県',   '千葉県'],
        ['東京都',   '東京都'],
        ['神奈川県',   '神奈川県'],
        ['新潟県',    '新潟県'],
        ['富山県',   '富山県'],
        ['石川県',   '石川県'],
        ['福井県',   '福井県'],
        ['山梨県',   '山梨県'],
        ['長野県',   '長野県'],
        ['岐阜県',   '岐阜県'],
        ['静岡県',   '静岡県'],
        ['愛知県',   '愛知県'],
        ['三重県',    '三重県'],
        ['滋賀県',   '滋賀県'],
        ['京都府',   '京都府'],
        ['大阪府',   '大阪府'],
        ['兵庫県',   '兵庫県'],
        ['奈良県',   '奈良県'],
        ['和歌山県',   '和歌山県'],
        ['鳥取県',    '鳥取県'],
       ['島根県',   '島根県'],
       ['岡山県',   '岡山県'],
       ['広島県',   '広島県'],
       ['山口県',   '山口県'],
       ['徳島県',    '徳島県'],
       ['香川県',   '香川県'],
       ['愛媛県',   '愛媛県'],
       ['高知県',   '高知県'],
       ['福岡県',    '福岡県'],
       ['佐賀県',   '佐賀県'],
       ['長崎県',   '長崎県'],
       ['熊本県',   '熊本県'],
       ['大分県',   '大分県'],
       ['宮崎県',   '宮崎県'],
       ['鹿児島県',   '鹿児島県'],
       ['沖縄県',    '沖縄県']],
       :selected => "東京都"
        %>

      <%= f.label :city, "市町村を入力してください" %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
  <br><br>
  <%= @user.pref %><%= @user.city %>
</h1>

</section>
</aside>
</div>